name = "AriA Latest"
author = "axiomeye"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4319f47e417dea77862d904ad31a0cba2f08bde6e2b5f12cdcb2ee390b739351"

[versions]
minecraft = "26.2"
fabric = "0.19.5"
