name = "AriA Cobblemon"
author = "axiomeye"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82e9fa8720cad8e179b200566d41dc1e89739ee3288ca27498f7f2d0eefee7da"

[versions]
minecraft = "1.21.1"
fabric = "0.19.5"
