name = "AriA Cobblemon"
author = "axiomeye"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10cb0d9327d3a241314a271f3f2daff39627a56b83b0c37fd040cbf56ee57eee"

[versions]
minecraft = "1.21.1"
fabric = "0.19.5"
