name = "AriA Cobblemon"
author = "axiomeye"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b165cb0315a771d261851c4ed42c2e97499f9d01dda7ca6a590c696944c2894"

[versions]
minecraft = "1.21.1"
fabric = "0.19.5"
