name = "AriA Latest"
author = "axiomeye"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b2cb4c60566f89261417cc7342dc3822c11317c3e47d6a3cc5afd9c32135899"

[versions]
minecraft = "26.2"
fabric = "0.19.5"
