name = "AriA Latest"
author = "axiomeye"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "277a016c53b7158fa604d7d5497f0c7ade5322ccc385f5e2e90babb249a12760"

[versions]
minecraft = "26.2"
fabric = "0.19.5"
