name = "AriA Latest"
author = "axiomeye"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b230eaaf6b066cd0dbfe161a886eb5c00576ddbfbdced9b18ef2f2f74655865"

[versions]
minecraft = "26.2"
fabric = "0.19.5"
